language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: 46.0
  sauce_connect: false
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install -g bower
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: OlzY+gZzbFJWRy1eEFSgns3vS+5gMyC6f2nSEx0Bu4B0nxWyYESfS2OacrY9ZlcDqNKGGY1g0NugXdCpgJyyrGB23NxW1QxpY72CfRRuzPTUlb8dsfXJmScVAWyisqozU66vxznLl68rGXMR07SWhSbGAkLT6YX8bBkvs96oOYtIG8bAqcWCspKGtK9Xn0dumxgBYjutIuw06cfteEP8niQdkQlsgSjslQQUWEOn9C4XScGXwt+GAY0FFhP5oxZIyUyiMseuR9g6jEd8jPdrFH9Uj1IPGjt3HijvQkiNKYo6zqxn+b01Qe/H+04cn6tmAMDxdDqmU6tABMs6B7wifEOwXGMDRZ6IyJsQiN4DZ/nLriSX1yvKNjgedX2u1xFJkKPCOqXzKaeAyE8MMpVZHM/8v+kruqhmCmshFMJR3JUTyPhELgplMY6sNIME8GUKLwaniqlsigmhjFImwQHgmpP5MZvSTRjVoSSmmPVjv/mwrclCSzPy1QtZ0u7/OjPZiyNK+5g3kx1hE0kCi5RpTigcB1z8ZjmCv0S68TmA8f+W4Ug80nKHyu3f+7gcqIenR4Uj2lLcBrhsQZfRMyL+x4l7B6XxIkx38MEHxTI/WcWUzNZdV53N3ci5pZqtYnLlnXOMenpfH5xE4rqucag4pgON8uKEk5fnKZmvnsTy/vU=
  - secure: pk8MxcozGeVZKiaX86hN/0BPEWLIBNx2fsqn4ZaikhVA1lDpAOqPNCu1I5+M6tMX6ARt8YMhxhxoGH/k8hKxPHrEOCUK4wyaWkEZC/G0pU2HeRnqCr22/U+SNrg8EnLlm71pnz7HuSTBxKzX0EWtmwCelpPF38rdORq5G/s0JN+F93g5LwipTZmyDp9oYpAqFOCdYtpkTPD/xCLpQ36pcPSNmK6rS95CJ+sGGv3p+sanZZHQ1nhONnytmNiXzScPO/QZ+N5Xkl2pOjGexRzTDLC42+fLw5pwu72dueY0DP0hB/2s7dIicVlzX1ZWSEhlweVy88RetiFCQ7teXOW1ryBYKb+tpVlWkHI2kGJeG9Z+NzFjlcUAJg3YIbP6If8FbyrwJ2gO7kuOe8pHFOAqAkDVXZpLTO0OifgnW3Mcn2ekBwlswjFDvbvhVzw/Pt2sxSTAfiri7CBxsITqNDlHV8V2x0dm5uE7RrkfE9TZl7NC9uzER+6yIkUp9jSiBOXrpVHqfXfSUXDRZtpn/jXYrMKb3Aa81RUKIO0YylD1jRemnRMyXGzvcZ/X0MOV47kQvBRvoj3HZX7s5/WV4xmSfr5BO/5KObLdhd2bRuuSBWCUeyNn2DJB0f/CZkdJCjTv0xtt7RgHwn8GpoAc9X98FeyMZJx/76veRAmpqbaHZzs=
